set encoding=utf-8

" Automatic reloading of vimrc
autocmd! bufwritepost vimrc source %

" Leader key
let mapleader = " "

" Line numbering
set number relativenumber

" Mouse and backspace
set mouse=a

" Copying and pasting
vnoremap <leader>y "+y
map <leader>y "+yy
map <leader>yy "+yy
map <leader>p "+p
map <leader>P "+P

" Syntax highlighting
syntax on

