" My vimrc

set encoding=utf-8

" Automatic reloading of vimrc
autocmd! bufwritepost vimrc source %

" Line numbering
set number relativenumber

" Mouse and backspace
set mouse=a
set bs=2

" Leader key
let mapleader = ","

" Copying and pasting
vnoremap <leader>c "+y
map <leader>c "+yy
map <leader>v "+P

" Duplicate line
map <leader>d yyp

" Syntax highlighting
filetype off
filetype plugin indent on
syntax on

" Spaces as TABs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Cursor settings
let &t_SI = "\e[5 q"
let &t_EI = "\e[1 q"
set ttimeout
set ttimeoutlen=1
set listchars=tab:>-,trail:~,extends:>,precedes:<,space:.
set ttyfast




" ====================================================================
" ==============================PATHOGEN==============================
" ====================================================================

execute pathogen#infect()

" ctrl-P
let g:ctrlp_max_height=30
set wildignore+=*.pyc
set wildignore+=*_build/*
set wildignore+=*/coverage/*

" Indent guides
let g:indentLine_char = '|'

" Commenter
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
let g:NERDTrimTrailingWhitespace = 1
map  <plug>NERDCommenterToggle

" NERDTree
map <leader>T :NERDTreeToggle<CR>

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_python_checkers = ['pyflakes', 'flake8']
" let g:syntastic_html_checkers = ['jshint']
" let g:syntastic_c_checkers = ['gcc']
" let g:syntastic_c_check_header = 1
" let g:syntastic_cpp_checkers = ['gcc']
" let g:syntastic_cpp_check_header = 1

" Nerd fonts
set guifont=Hack\ Nerd\ Font\ 13

