-- vim.api.nvim_set_option('coc_global_extensions', {'coc-pyright', 'coc-json', 'coc-yaml', 'coc-vimlsp', 'coc-prettier', 'coc-explorer', 'coc-lists', 'coc-pydocstring', 'coc-markdownlint'})
-- vim.g.coc_global_extensions = {'coc-pyright', 'coc-json', 'coc-yaml', 'coc-vimlsp', 'coc-prettier', 'coc-explorer', 'coc-lists', 'coc-pydocstring', 'coc-markdownlint'}
